import type { TrendingProjectCardProps } from "../components/TrendingProjectCard";
import type { BuilderSpotlight } from "../components/BuildersSpotlight";

export const MOCK_PROJECTS: TrendingProjectCardProps[] = [
  {
    id: "1",
    title: "App de reservas para peluquerías",
    description: "SaaS para gestionar citas y pagos online. Integración con calendario y recordatorios.",
    currentDay: 12,
    totalDays: 30,
    progressPercent: 40,
    authorUsername: "mariag",
    authorName: "María García",
    badges: ["trending"],
    height: "tall",
  },
  {
    id: "2",
    title: "CRM para pymes",
    description: "CRM simple y asequible para pequeñas empresas.",
    currentDay: 18,
    totalDays: 30,
    progressPercent: 60,
    authorUsername: "carlosr",
    authorName: "Carlos Ruiz",
    badges: ["ultimos"],
    height: "short",
  },
  {
    id: "3",
    title: "Marketplace de cursos locales",
    description: "Conectar profesores y alumnos en la misma ciudad. Enfoque en clases presenciales y talleres.",
    currentDay: 8,
    totalDays: 30,
    progressPercent: 27,
    authorUsername: "analopez",
    authorName: "Ana López",
    badges: [],
    height: "medium",
  },
  {
    id: "4",
    title: "Bot de IA para soporte",
    description: "Chatbot entrenado con la base de conocimiento de tu empresa.",
    currentDay: 25,
    totalDays: 30,
    progressPercent: 85,
    authorUsername: "pablom",
    authorName: "Pablo Martín",
    badges: ["trending", "ultimos"],
    height: "medium",
  },
  {
    id: "5",
    title: "Plataforma de pagos para freelancers",
    description: "Facturación y cobros simplificados para trabajadores independientes.",
    currentDay: 5,
    totalDays: 30,
    progressPercent: 17,
    authorUsername: "laurav",
    authorName: "Laura Vega",
    badges: [],
    height: "short",
  },
  {
    id: "6",
    title: "Herramienta de generación de logos",
    description: "IA que crea identidad visual en segundos. Variaciones y exportación en alta resolución.",
    currentDay: 22,
    totalDays: 30,
    progressPercent: 73,
    authorUsername: "mariag",
    authorName: "María García",
    badges: ["trending"],
    height: "tall",
  },
];

export const MOCK_BUILDERS_SPOTLIGHT: BuilderSpotlight[] = [
  {
    username: "mariag",
    displayName: "María García",
    bio: "Builder enfocada en SaaS B2B. 30 días para validar.",
    streakDays: 12,
    level: "Builder",
    completedProjects: 2,
  },
  {
    username: "carlosr",
    displayName: "Carlos Ruiz",
    bio: "Validando ideas en 30 días. Primer cliente conseguido.",
    streakDays: 18,
    level: "Builder",
    completedProjects: 1,
  },
  {
    username: "analopez",
    displayName: "Ana López",
    bio: "MVP en 30 días. Construyendo en público.",
    streakDays: 21,
    level: "Pro",
    completedProjects: 3,
  },
];
